spring:
  #datasource:
  #  url: ${datasource_url}
  #  username: ${datasource_username}
  #  password: ${datasource_password}
  #  driver-class-name: com.mysql.cj.jdbc.Driver
  logging:
    level:
      org.hibernate.SQL: trace
      org.hibernate.type.descriptor.sql.BasicBinder: trace
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  servlet:
    encoding:
      force-response: true
  error:
    include-exception: false
    include-message: always
    include-stacktrace: always
    whitelabel.enabled: true
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420



